from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils import timezone
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
import csv
from .models import Report
from threat_detection.models import ThreatLog
from monitoring.models import HVDCReading

@login_required
def report_list(request):
    # Admin sees ALL reports, others see only their own
    if request.user.is_admin():
        reports = Report.objects.all().order_by('-generated_at')
    else:
        reports = Report.objects.filter(generated_by=request.user).order_by('-generated_at')
    return render(request, 'reports/list.html', {'reports': reports})

@login_required
def generate_pdf_report(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="hvdc_threat_report.pdf"'
    doc = SimpleDocTemplate(response, pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []
    elements.append(Paragraph('HVDC CyberSec — Threat Analysis Report', styles['Title']))
    elements.append(Spacer(1, 12))
    elements.append(Paragraph(f'Generated: {timezone.now().strftime("%Y-%m-%d %H:%M")}', styles['Normal']))
    elements.append(Paragraph(f'Generated by: {request.user.username}', styles['Normal']))
    elements.append(Spacer(1, 20))
    threats = ThreatLog.objects.order_by('-detected_at')[:50]
    data = [['Attack Type', 'Severity', 'Confidence', 'Source IP', 'Detected At']]
    for t in threats:
        data.append([
            t.get_attack_type_display(),
            t.severity.upper(),
            f'{t.confidence_score:.2f}',
            str(t.source_ip or '—'),
            t.detected_at.strftime('%Y-%m-%d %H:%M')
        ])
    tbl = Table(data, colWidths=[120, 80, 80, 120, 120])
    tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1A3C5E')),
        ('TEXTCOLOR',  (0, 0), (-1, 0), colors.white),
        ('FONTNAME',   (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE',   (0, 0), (-1, 0), 11),
        ('GRID',       (0, 0), (-1, -1), 0.5, colors.grey),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#EAF4FB')]),
        ('FONTSIZE',   (0, 1), (-1, -1), 9),
        ('ALIGN',      (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN',     (0, 0), (-1, -1), 'MIDDLE'),
        ('PADDING',    (0, 0), (-1, -1), 6),
    ]))
    elements.append(tbl)
    doc.build(elements)

    # Save to Report model
    Report.objects.create(
        title=f'Threat Analysis Report — {timezone.now().strftime("%B %d, %Y")}',
        report_type='threat_summary',
        generated_by=request.user,
        period_from=timezone.now().date(),
        period_to=timezone.now().date(),
        summary=f'Auto-generated report. {threats.count()} threats included.'
    )
    return response

@login_required
def generate_csv_report(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="hvdc_threats.csv"'
    writer = csv.writer(response)
    writer.writerow(['ID', 'Attack Type', 'Severity', 'Confidence', 'Source IP', 'DC Voltage', 'DC Current', 'Active Power', 'Packet Rate', 'Detected At'])
    for t in ThreatLog.objects.all().order_by('-detected_at'):
        writer.writerow([
            t.id, t.attack_type, t.severity,
            t.confidence_score, t.source_ip or '—',
            t.dc_voltage, t.dc_current, t.active_power,
            t.network_packet_rate, t.detected_at
        ])
    return response