# Generated by Django 5.2.11 on 2026-03-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('warning', 'Warning'), ('offline', 'Offline')], default='online', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('details', models.TextField(blank=True)),
            ],
        ),
    ]
