# Generated by Django 5.2.11 on 2026-03-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HVDCReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dc_voltage', models.FloatField(help_text='DC Voltage in kV')),
                ('dc_current', models.FloatField(help_text='DC Current in kA')),
                ('ac_voltage_rectifier', models.FloatField(help_text='AC voltage at rectifier in kV')),
                ('ac_voltage_inverter', models.FloatField(help_text='AC voltage at inverter in kV')),
                ('active_power', models.FloatField(help_text='Active power in MW')),
                ('reactive_power', models.FloatField(help_text='Reactive power in MVAR')),
                ('firing_angle_rectifier', models.FloatField(help_text='Degrees')),
                ('extinction_angle_inverter', models.FloatField(help_text='Degrees')),
                ('converter_status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('fault', 'Fault')], default='normal', max_length=20)),
                ('network_packet_rate', models.IntegerField(default=0, help_text='packets/sec')),
                ('communication_latency', models.FloatField(default=0.0, help_text='ms')),
                ('data_source', models.CharField(default='sensor', max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('protocol', models.CharField(max_length=20)),
                ('packet_size', models.IntegerField()),
                ('packet_count', models.IntegerField()),
                ('is_anomalous', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
