# Generated by Django 5.2.11 on 2026-03-03 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('threshold', models.FloatField(default=0.5)),
                ('is_active', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trained_on', models.IntegerField(default=0, help_text='Number of training samples')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('attack_type', models.CharField(choices=[('normal', 'Normal'), ('dos', 'Denial of Service'), ('fdi', 'False Data Injection'), ('cmd_manip', 'Command Manipulation'), ('replay', 'Replay Attack')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('dc_voltage', models.FloatField()),
                ('dc_current', models.FloatField()),
                ('active_power', models.FloatField()),
                ('network_packet_rate', models.IntegerField(default=0)),
                ('communication_latency', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_threats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
